# Generated by Django 5.2.9 on 2026-06-26 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('message', '0005_groupmessage_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ('created_at',), 'verbose_name': 'پیام گروهی', 'verbose_name_plural': 'پیام\u200cهای گروهی'},
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='content',
            field=models.TextField(blank=True, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='auth.group', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'متن'), ('sticker', 'استیکر'), ('file', 'فایل')], default='text', max_length=20, verbose_name='نوع پیام'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='متن'),
        ),
    ]
