# Generated by Codex for portfolio detail fields.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='detail_description',
            field=models.TextField(blank=True, verbose_name='جزئیات کامل نمونه کار'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/details/', verbose_name='تصویر جزئیات'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='portfolio/files/', verbose_name='فایل پروژه'),
        ),
    ]