"""
Django settings for pouriabaghban3 project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4k!didb)t*1*vc50xox(ngdl-wtpb)ad_gj8@)s&p_*m*-krr$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "pouriabaghban.ir",
    "www.pouriabaghban.ir",
    ".pouriabaghban.ir",
    ".runflare.com",
    ".runflare.app",
    "localhost",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_jalali',
    'rosetta',
    'rest_framework',
    'ckeditor',
    "ckeditor_uploader",
    
    # Local apps
    'message.apps.MessageConfig',
    'blog.apps.BlogConfig',
    'gallery.apps.GalleryConfig',
    'contact.apps.ContactConfig',
    'pages.apps.PagesConfig',
    'podcast_app.apps.PodcastAppConfig',
    'dashboard.apps.DashboardConfig',
    'admin_chat.apps.AdminChatConfig',
    'kskh.apps.KskhConfig',
]

# Optional: enable Django Channels if installed
try:
    import channels  # noqa: F401
    INSTALLED_APPS.insert(0, 'channels')
except Exception:
    pass

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pouriabaghban3.middleware.AdminSecurityMiddleware',
]

ROOT_URLCONF = 'pouriabaghban3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR.joinpath('templates'))],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pages.context_processors.site_context',
                'pages.context_processors.footer.footer_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'pouriabaghban3.wsgi.application'

# ASGI / Channels settings (optional)
ASGI_APPLICATION = 'pouriabaghban3.asgi.application'

REDIS_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
            "capacity": int(os.environ.get("CHANNEL_LAYER_CAPACITY", "1500")),
            "expiry": int(os.environ.get("CHANNEL_LAYER_EXPIRY", "60")),
            "group_expiry": int(os.environ.get("CHANNEL_LAYER_GROUP_EXPIRY", "86400")),
        },
    },
}

USE_REDIS = os.environ.get("USE_REDIS", "0") == "1"

REDIS_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1")

if USE_REDIS:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": os.environ.get("CACHE_URL", REDIS_URL),
            "TIMEOUT": int(os.environ.get("CACHE_DEFAULT_TIMEOUT", "300")),
            "KEY_PREFIX": os.environ.get("CACHE_KEY_PREFIX", "pouriabaghban"),
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "local-dev-cache",
            "TIMEOUT": int(os.environ.get("CACHE_DEFAULT_TIMEOUT", "300")),
            "KEY_PREFIX": os.environ.get("CACHE_KEY_PREFIX", "pouriabaghban"),
        }
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
 
BASE_DIR = Path(__file__).resolve().parent.parent

USE_MYSQL = os.getenv("USE_MYSQL", "0") == "1"

if USE_MYSQL:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("DB_NAME", "pouriabagtw_db"),
            "USER": os.getenv("DB_USER", "root"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "127.0.0.1"),
            "PORT": os.getenv("DB_PORT", "3306"),
            "OPTIONS": {
                "charset": "utf8mb4",
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa'

LANGUAGES = [
    ('fa', 'Persian'),
    ('de', 'German'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login settings
LOGIN_URL = 'kskh:login'
LOGIN_REDIRECT_URL = 'kskh:index'
LOGOUT_REDIRECT_URL = 'kskh:login'

CHAT_UPLOAD_CHUNK_SIZE = 1024 * 1024
CHAT_MAX_ATTACHMENT_SIZE = 300 * 1024 * 1024
CHAT_ALLOWED_ATTACHMENT_EXTENSIONS = [
    ".jpg", ".jpeg", ".png", ".gif", ".webp", ".avif", ".apng", ".bmp",
    ".heic", ".heif", ".ico", ".jfif", ".svg", ".tif", ".tiff", ".pdf", ".mp4", ".mov",
    ".avi", ".mkv", ".zip", ".doc", ".docx", ".xls", ".xlsx", ".ppt",
    ".pptx", ".txt",
]

# Session / CSRF defaults. Production values are enforced again below.
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'True') == 'True'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'True') == 'True'
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"

# Email settings Ø¨Ø±Ø§ÛŒ Ø§Ø±Ø³Ø§Ù„ ÛŒØ§Ø¯Ø¢ÙˆØ±ÛŒ Ù¾Ø³ÙˆØ±Ø¯
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'poriab426@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'vjfq gdgg fhvm jfye')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'poriab426@gmail.com')

# Admins who receive error emails from Django when DEBUG=False
ADMINS = [
    ('Site Admin', os.environ.get('ADMIN_EMAIL', 'poriab426@gmail.com')),
]

# The sender address for error emails
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

# Security-related settings: enable recommended headers in production via env vars
# These are safe defaults for dev (off) and can be enabled in production by setting
# the corresponding environment variables to 'True'.
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False') == 'True'
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'False') == 'True'
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False') == 'True'
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', str(SESSION_COOKIE_SECURE)) == 'True'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', str(CSRF_COOKIE_SECURE)) == 'True'

# X-Content-Type-Options and Referrer-Policy can be controlled by middleware or webserver.

# Logging: email admins on errors when DEBUG=False
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        }
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins', 'console'],
            'level': 'ERROR',
            'propagate': True,
        },
        # you can add other specific loggers here
    },
}
# Podcast security settings
JWT_EXPIRATION = 300
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# Audio upload limits for podcast admin
DATA_UPLOAD_MAX_MEMORY_SIZE = 30 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 30 * 1024 * 1024
MAX_AUDIO_FILE_SIZE = 30 * 1024 * 1024
ALLOWED_AUDIO_EXTENSIONS = ['.mp3', '.wav', '.ogg', '.m4a', '.flac', '.aac']
ALLOWED_AUDIO_CONTENT_TYPES = [
    'audio/mpeg',
    'audio/mp3',
    'audio/wav',
    'audio/x-wav',
    'audio/ogg',
    'audio/mp4',
    'audio/x-m4a',
    'audio/flac',
    'audio/aac',
]


# CSRF / HTTPS proxy settings for production behind Runflare.
CSRF_TRUSTED_ORIGINS = [
    "https://pouriabaghban.ir",
    "https://www.pouriabaghban.ir",
    "https://*.pouriabaghban.ir",
    "https://*.runflare.com",
    "https://*.runflare.app",
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_HTTPONLY = True
CSRF_FAILURE_VIEW = "pages.views.csrf_failure"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
}

# Runflare public static/media fix
# Runflare public static/media fix
STATIC_URL = "/public/static/"
STATIC_ROOT = BASE_DIR / "public" / "static"

STATICFILES_DIRS = [
    BASE_DIR / "staticfiles",
]

MEDIA_URL = "/public/media/"
MEDIA_ROOT = BASE_DIR / "public" / "media"
PROTECTED_MEDIA_ROOT = BASE_DIR / "protected_media"
CKEDITOR_UPLOAD_PATH = "ckeditor/uploads/"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}
