# Generated by Django 5.2.5 on 2026-06-30 11:42

import django.db.models.deletion
import kskh.models
import kskh.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KskhPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180, validators=[kskh.validators.validate_clean_text])),
                ('slug', models.SlugField(blank=True, max_length=210, unique=True)),
                ('description', models.TextField(blank=True, validators=[kskh.validators.validate_clean_text])),
                ('file', models.FileField(upload_to=kskh.models.kskh_upload_to, validators=[kskh.validators.validate_kskh_file])),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False)),
                ('file_extension', models.CharField(blank=True, editable=False, max_length=20)),
                ('kind', models.CharField(choices=[('apk', 'APK'), ('exe', 'EXE'), ('zip', 'ZIP'), ('config', 'Config'), ('other', 'Other')], default='other', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kskh_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KSKH post',
                'verbose_name_plural': 'KSKH posts',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='KskhComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(validators=[kskh.validators.validate_clean_text])),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='kskh.kskhcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kskh_comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kskh.kskhpost')),
            ],
            options={
                'verbose_name': 'KSKH comment',
                'verbose_name_plural': 'KSKH comments',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='KskhReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='kskh.kskhpost')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kskh_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('post', 'user'), name='unique_kskh_user_reaction'), models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('post', 'session_key'), name='unique_kskh_session_reaction')],
            },
        ),
    ]
