# Generated by Django 5.2.14 on 2026-06-30 12:00

from django.db import migrations, models


def normalize_old_kinds(apps, schema_editor):
    KskhPost = apps.get_model("kskh", "KskhPost")
    KskhPost.objects.filter(kind="apk").update(kind="app")
    KskhPost.objects.filter(kind__in=["exe", "zip"]).update(kind="other")


class Migration(migrations.Migration):

    dependencies = [
        ('kskh', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalize_old_kinds, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='kskhcomment',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kskhpost',
            name='kind',
            field=models.CharField(choices=[('app', 'App'), ('config', 'Config'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
