# Generated by Django 5.2.9 on 2026-06-24 20:01

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('speaker', models.CharField(max_length=100, verbose_name='گوینده')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('audio_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PureWindowsPath('E:/Desktop/pouriabaghban3/protected_media/podcasts')), upload_to='', verbose_name='فایل صوتی')),
                ('cover_image', models.ImageField(upload_to='podcast_covers/', verbose_name='تصویر کاور')),
                ('duration', models.CharField(max_length=20, verbose_name='مدت زمان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'پادکست',
                'verbose_name_plural': 'پادکست\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
