# Generated by Django 5.2.9 on 2026-06-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_app', '0002_podcast_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='cover_image',
            field=models.ImageField(upload_to='podcast_covers/', verbose_name='عکس آلبوم'),
        ),
    ]
