# Generated by Django 5.2.14 on 2026-06-25 14:02

import django.core.files.storage
import pathlib
import podcast_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_app', '0004_poetry_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ['-created_at'], 'verbose_name': 'پادکست', 'verbose_name_plural': 'پادکست\u200cها'},
        ),
        migrations.AlterField(
            model_name='podcast',
            name='audio_file',
            field=models.FileField(blank=True, help_text='فقط فایل صوتی با حجم حداکثر ۳۰ مگابایت پذیرفته می\u200cشود.', null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PureWindowsPath('E:/Desktop/pouriabaghban3/protected_media/podcasts')), upload_to='', validators=[podcast_app.models.validate_audio_file_extension, podcast_app.models.validate_audio_file_size], verbose_name='فایل صوتی'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='duration',
            field=models.CharField(blank=True, max_length=20, verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='speaker',
            field=models.CharField(max_length=100, verbose_name='گوینده / نویسنده'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='transcript',
            field=models.TextField(blank=True, verbose_name='متن پادکست'),
        ),
    ]
