# Generated by Django 5.2.14 on 2026-07-01 20:31

import django.core.files.storage
import pathlib
import podcast_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_app', '0007_podcast_content_type_specialpoem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='audio_file',
            field=models.FileField(blank=True, help_text='فقط فایل صوتی با حجم حداکثر ۳۰ مگابایت پذیرفته می\u200cشود.', null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PureWindowsPath('E:/Desktop/pouriabaghban/protected_media/podcasts')), upload_to='', validators=[podcast_app.models.validate_audio_file_extension, podcast_app.models.validate_audio_file_size], verbose_name='فایل صوتی'),
        ),
    ]
