# Generated by Django 5.2.14 on 2026-07-02 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast_app', '0008_alter_podcast_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد بازدید'),
        ),
    ]
