# Generated by Django 4.0.10 on 2025-12-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='کلید')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'محتوای صفحه',
                'verbose_name_plural': 'محتویات صفحات',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام سایت')),
                ('site_description', models.TextField(verbose_name='توضیح سایت')),
                ('logo', models.ImageField(upload_to='pages/', verbose_name='لوگو')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='آیکون')),
                ('owner_name', models.CharField(max_length=100, verbose_name='نام مالک')),
                ('owner_title', models.CharField(max_length=200, verbose_name='تخصص/شغل')),
                ('owner_bio', models.TextField(verbose_name='بیوگرافی مالک')),
                ('owner_image', models.ImageField(upload_to='pages/', verbose_name='عکس مالک')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='pages/', verbose_name='رزومه (PDF)')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مهارت')),
                ('percentage', models.IntegerField(default=50, help_text='0 تا 100', verbose_name='درصد مهارت')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='دسته\u200cبندی')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='آیکن FontAwesome')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت\u200cها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'توییتر'), ('facebook', 'فیس\u200cبوک'), ('instagram', 'اینستاگرام'), ('linkedin', 'لینکدین'), ('youtube', 'یوتیوب'), ('whatsapp', 'واتس\u200cاپ'), ('telegram', 'تلگرام')], max_length=20, verbose_name='پلتفرم')),
                ('url', models.URLField(verbose_name='آدرس')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='آیکن FontAwesome')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'لینک شبکه اجتماعی',
                'verbose_name_plural': 'لینک\u200cهای شبکه\u200cهای اجتماعی',
                'unique_together': {('platform',)},
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('index', 'صفحه اصلی'), ('blog', 'بلاگ'), ('gallery', 'گالری'), ('contact', 'تماس با ما'), ('about', 'درباره ما')], max_length=20, verbose_name='صفحه')),
                ('section', models.CharField(choices=[('hero', '1️⃣ قسمت بالای صفحه (Hero) - عنوان و تصویر بزرگ'), ('header', '2️⃣ سربرگ - منو و لوگو'), ('footer', '3️⃣ پایین صفحه - لینک\u200cها و اطلاعات'), ('about', '4️⃣ درباره ما - معرفی و بیوگرافی'), ('biography', '5️⃣ بیوگرافی تکمیلی - تاریخچه و پیشینه'), ('testimonials', '6️⃣ نظرات کلاینت\u200cها - توصیه\u200cها'), ('skills', '7️⃣ مهارت\u200cها - تکنولوژی\u200cها و زبان\u200cهای برنامه\u200cنویسی'), ('expertise', '8️⃣ تخصص\u200cها - حوزه\u200cهای کاری'), ('certifications', '9️⃣ گواهینامه\u200cها - مدارک و دوره\u200cهای اعتباری'), ('services', '🔟 خدمات - سرویس\u200cهای ارائه شده'), ('service_details', '1️⃣1️⃣ جزئیات خدمات - توضیح کامل خدمات'), ('projects', '1️⃣2️⃣ پروژه\u200cهای نمونه - کارهای انجام شده'), ('project_showcase', '1️⃣3️⃣ نمایش پروژه\u200cها - پروژه\u200cهای برجسته'), ('team', '1️⃣4️⃣ تیم - اعضای تیم'), ('team_details', '1️⃣5️⃣ جزئیات تیم - معرفی اعضا'), ('partners', '1️⃣6️⃣ شریک\u200cها - شریک\u200cهای کسب\u200cوکاری'), ('portfolio', '1️⃣7️⃣ نمونه\u200cکارها - پورتفولیو'), ('achievements', '1️⃣8️⃣ دستاوردها - موفقیت\u200cها و جوایز'), ('statistics', '1️⃣9️⃣ آمار و ارقام - نمودار و آمار'), ('process', '2️⃣0️⃣ فرآیند کاری - مراحل انجام کار'), ('workflow', '2️⃣1️⃣ جریان کاری - نحوه همکاری'), ('timeline', '2️⃣2️⃣ جدول زمانی - مراحل و سر فاصل'), ('experience', '2️⃣3️⃣ تجربه - سابقه کاری'), ('values', '2️⃣4️⃣ ارزش\u200cهای ما - اصول و باورها'), ('mission', '2️⃣5️⃣ ماموریت ما - هدف و راهبرد'), ('cta', '2️⃣6️⃣ فراخوان عمل - دکمه\u200cهای فراخوان'), ('contact_form', '2️⃣7️⃣ فرم تماس - فرم درخواست'), ('faq', '2️⃣8️⃣ پرسش\u200cهای متداول - Q&A'), ('blog_preview', '2️⃣9️⃣ پیش\u200cنمایش بلاگ - پست\u200cهای اخیر'), ('gallery_preview', '3️⃣0️⃣ پیش\u200cنمایش گالری - تصاویر برجسته')], max_length=20, verbose_name='بخش')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='تصویر')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='تصویر دوم')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='تصویر سوم')),
                ('text_field_1', models.TextField(blank=True, verbose_name='متن 1')),
                ('text_field_2', models.TextField(blank=True, verbose_name='متن 2')),
                ('text_field_3', models.TextField(blank=True, verbose_name='متن 3')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='متن دکمه')),
                ('button_url', models.URLField(blank=True, verbose_name='آدرس لینک دکمه')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'بخش صفحه',
                'verbose_name_plural': 'بخش\u200cهای صفحات',
                'ordering': ['page', 'section', 'order'],
                'unique_together': {('page', 'section', 'order')},
            },
        ),
    ]
