# Generated by Django 5.2.9 on 2025-12-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField(choices=[(400, 'خطای 400 - درخواست نامعتبر'), (403, 'خطای 403 - دسترسی ممنوع'), (404, 'خطای 404 - صفحه پیدا نشد'), (500, 'خطای 500 - خطای سرور')], unique=True, verbose_name='کد وضعیت')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان فارسی')),
                ('description', models.TextField(verbose_name='توضیح فارسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='errors/', verbose_name='تصویر خطا')),
                ('button_text', models.CharField(default='بازگشت به صفحه اصلی', max_length=100, verbose_name='متن دکمه')),
                ('button_url', models.CharField(default='/', max_length=200, verbose_name='آدرس دکمه')),
            ],
            options={
                'verbose_name': 'صفحه خطا',
                'verbose_name_plural': 'صفحات خطا',
            },
        ),
    ]
