# Generated by Django 5.2.9 on 2025-12-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_errorpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کلاینت')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان/شرکت')),
                ('message', models.TextField(verbose_name='پیام/نظر')),
                ('rating', models.IntegerField(choices=[(1, '1 ستاره'), (2, '2 ستاره'), (3, '3 ستاره'), (4, '4 ستاره'), (5, '5 ستاره')], default=5, verbose_name='امتیاز')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='عکس پروفایل')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('order', models.IntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'نظر/توصیه',
                'verbose_name_plural': 'نظرات و توصیه\u200cها',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
