# Generated by Django 5.2.9 on 2026-06-24 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_podcast'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Podcast',
        ),
    ]
