# Generated by Django 5.2.9 on 2026-06-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_delete_podcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pages/footer/', verbose_name='لوگوی فوتر')),
                ('description', models.TextField(blank=True, verbose_name='متن معرفی فوتر')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل فوتر')),
                ('copyright_text', models.CharField(blank=True, max_length=200, verbose_name='متن کپی\u200cرایت')),
                ('copyright_year', models.CharField(default='2024', max_length=10, verbose_name='سال کپی\u200cرایت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'تنظیمات فوتر',
                'verbose_name_plural': 'تنظیمات فوتر',
            },
        ),
        migrations.CreateModel(
            name='HomePageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('comment', models.TextField(max_length=500, verbose_name='متن نظر')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شود')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'نظر کاربر صفحه اصلی',
                'verbose_name_plural': 'نظرات کاربران صفحه اصلی',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='عنوان')),
                ('url', models.CharField(help_text='مثال: /blog/ یا #about یا https://example.com', max_length=300, verbose_name='آدرس لینک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('opens_new_tab', models.BooleanField(default=False, verbose_name='باز شدن در تب جدید')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'آیتم نوبار',
                'verbose_name_plural': 'آیتم\u200cهای نوبار',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='section',
            field=models.CharField(choices=[('hero', '1️⃣ قسمت بالای صفحه (Hero) - عنوان و تصویر بزرگ'), ('header', '2️⃣ سربرگ - منو و لوگو'), ('footer', '3️⃣ پایین صفحه - لینک\u200cها و اطلاعات'), ('about', '4️⃣ درباره ما - معرفی و بیوگرافی'), ('biography', '5️⃣ بیوگرافی تکمیلی - تاریخچه و پیشینه'), ('testimonials', '6️⃣ نظرات کلاینت\u200cها - توصیه\u200cها'), ('comments', 'نظرات کاربران صفحه اصلی'), ('skills', '7️⃣ مهارت\u200cها - تکنولوژی\u200cها و زبان\u200cهای برنامه\u200cنویسی'), ('expertise', '8️⃣ تخصص\u200cها - حوزه\u200cهای کاری'), ('certifications', '9️⃣ گواهینامه\u200cها - مدارک و دوره\u200cهای اعتباری'), ('services', '🔟 خدمات - سرویس\u200cهای ارائه شده'), ('service_details', '1️⃣1️⃣ جزئیات خدمات - توضیح کامل خدمات'), ('projects', '1️⃣2️⃣ پروژه\u200cهای نمونه - کارهای انجام شده'), ('project_showcase', '1️⃣3️⃣ نمایش پروژه\u200cها - پروژه\u200cهای برجسته'), ('team', '1️⃣4️⃣ تیم - اعضای تیم'), ('team_details', '1️⃣5️⃣ جزئیات تیم - معرفی اعضا'), ('partners', '1️⃣6️⃣ شریک\u200cها - شریک\u200cهای کسب\u200cوکاری'), ('portfolio', '1️⃣7️⃣ نمونه\u200cکارها - پورتفولیو'), ('achievements', '1️⃣8️⃣ دستاوردها - موفقیت\u200cها و جوایز'), ('statistics', '1️⃣9️⃣ آمار و ارقام - نمودار و آمار'), ('process', '2️⃣0️⃣ فرآیند کاری - مراحل انجام کار'), ('workflow', '2️⃣1️⃣ جریان کاری - نحوه همکاری'), ('timeline', '2️⃣2️⃣ جدول زمانی - مراحل و سر فاصل'), ('experience', '2️⃣3️⃣ تجربه - سابقه کاری'), ('values', '2️⃣4️⃣ ارزش\u200cهای ما - اصول و باورها'), ('mission', '2️⃣5️⃣ ماموریت ما - هدف و راهبرد'), ('cta', '2️⃣6️⃣ فراخوان عمل - دکمه\u200cهای فراخوان'), ('contact_form', '2️⃣7️⃣ فرم تماس - فرم درخواست'), ('faq', '2️⃣8️⃣ پرسش\u200cهای متداول - Q&A'), ('blog_preview', '2️⃣9️⃣ پیش\u200cنمایش بلاگ - پست\u200cهای اخیر'), ('gallery_preview', '3️⃣0️⃣ پیش\u200cنمایش گالری - تصاویر برجسته')], max_length=20, verbose_name='بخش'),
        ),
    ]
