# Generated by Django 5.2.9 on 2026-06-28 12:10

from django.db import migrations, models


def copy_existing_persian_content(apps, schema_editor):
    PageSection = apps.get_model('pages', 'PageSection')
    PageContent = apps.get_model('pages', 'PageContent')
    NavbarItem = apps.get_model('pages', 'NavbarItem')
    FooterSettings = apps.get_model('pages', 'FooterSettings')

    for section in PageSection.objects.all().iterator():
        update_fields = []
        for source, target in (
            ('title', 'title_fa'),
            ('description', 'description_fa'),
            ('text_field_1', 'text_field_1_fa'),
            ('button_text', 'button_text_fa'),
        ):
            if not getattr(section, target) and getattr(section, source):
                setattr(section, target, getattr(section, source))
                update_fields.append(target)
        if update_fields:
            section.save(update_fields=update_fields)

    for content in PageContent.objects.all().iterator():
        update_fields = []
        for source, target in (('title', 'title_fa'), ('content', 'content_fa')):
            if not getattr(content, target) and getattr(content, source):
                setattr(content, target, getattr(content, source))
                update_fields.append(target)
        if update_fields:
            content.save(update_fields=update_fields)

    for item in NavbarItem.objects.all().iterator():
        if not item.title_fa and item.title:
            item.title_fa = item.title
            item.save(update_fields=['title_fa'])

    for footer in FooterSettings.objects.all().iterator():
        update_fields = []
        for source, target in (('description', 'description_fa'), ('copyright_text', 'copyright_text_fa')):
            if not getattr(footer, target) and getattr(footer, source):
                setattr(footer, target, getattr(footer, source))
                update_fields.append(target)
        if update_fields:
            footer.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_footersettings_homepagecomment_navbaritem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='copyright_text_de',
            field=models.CharField(blank=True, max_length=200, verbose_name='Copyright text (German)'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='copyright_text_fa',
            field=models.CharField(blank=True, max_length=200, verbose_name='Copyright text (Persian)'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='description_de',
            field=models.TextField(blank=True, verbose_name='Footer description (German)'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='description_fa',
            field=models.TextField(blank=True, verbose_name='Footer description (Persian)'),
        ),
        migrations.AddField(
            model_name='navbaritem',
            name='title_de',
            field=models.CharField(blank=True, max_length=80, verbose_name='Title (German)'),
        ),
        migrations.AddField(
            model_name='navbaritem',
            name='title_fa',
            field=models.CharField(blank=True, max_length=80, verbose_name='Title (Persian)'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='content_de',
            field=models.TextField(blank=True, verbose_name='Page content (German)'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='content_fa',
            field=models.TextField(blank=True, verbose_name='Page content (Persian)'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='title_de',
            field=models.CharField(blank=True, max_length=200, verbose_name='Page title (German)'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='title_fa',
            field=models.CharField(blank=True, max_length=200, verbose_name='Page title (Persian)'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='button_text_de',
            field=models.CharField(blank=True, max_length=100, verbose_name='Button text (German)'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='button_text_fa',
            field=models.CharField(blank=True, max_length=100, verbose_name='Button text (Persian)'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='description_de',
            field=models.TextField(blank=True, verbose_name='Description (German)'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='description_fa',
            field=models.TextField(blank=True, verbose_name='Description (Persian)'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='text_field_1_de',
            field=models.TextField(blank=True, verbose_name='Text 1 (German)'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='text_field_1_fa',
            field=models.TextField(blank=True, verbose_name='Text 1 (Persian)'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='title_de',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (German)'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='title_fa',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Persian)'),
        ),
        migrations.RunPython(copy_existing_persian_content, migrations.RunPython.noop),
    ]
