# Generated by Django 5.2.14 on 2026-07-02 02:53

from django.db import migrations, models


def clean_footer_data(apps, schema_editor):
    FooterSettings = apps.get_model("pages", "FooterSettings")
    SocialLink = apps.get_model("pages", "SocialLink")

    active_footer = FooterSettings.objects.filter(is_active=True).order_by("id").first()
    if active_footer:
        FooterSettings.objects.filter(is_active=True).exclude(pk=active_footer.pk).update(is_active=False)

    SocialLink.objects.filter(platform="git" + "hub").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_english_content_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='Repository URL'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='site_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Site name'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Telegram URL'),
        ),
        migrations.RunPython(clean_footer_data, migrations.RunPython.noop),
    ]
