# Generated by Django 4.0.10 on 2025-12-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('is_replied', models.BooleanField(default=False, verbose_name='پاسخ داده شده')),
                ('reply_message', models.TextField(blank=True, null=True, verbose_name='پیام پاسخ')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام های تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل پاسخ')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتساپ')),
                ('telegram', models.CharField(blank=True, max_length=50, verbose_name='تلگرام')),
                ('instagram', models.CharField(blank=True, max_length=50, verbose_name='اینستاگرام')),
                ('linkedin', models.CharField(blank=True, max_length=100, verbose_name='لینکدین')),
            ],
            options={
                'verbose_name': 'تنظیمات تماس',
                'verbose_name_plural': 'تنظیمات تماس',
            },
        ),
    ]
