# Generated by Django 5.2.9 on 2025-12-03 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', '🔑 ادمین - دسترسی کامل'), ('author', '✍️ نویسنده - می\u200cتواند پست بنویسد'), ('editor', '📝 ویرایشگر - می\u200cتواند پست\u200cهای دیگران را ویرایش کند'), ('moderator', '🛡️ مدیریت\u200cکننده - می\u200cتواند کامنت\u200cها را تایید کند'), ('subscriber', '👤 مشترک - فقط می\u200cتواند بخواند')], max_length=20, verbose_name='نقش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('can_write', models.BooleanField(default=False, verbose_name='می\u200cتواند بنویسد')),
                ('can_edit', models.BooleanField(default=False, verbose_name='می\u200cتواند ویرایش کند')),
                ('can_delete', models.BooleanField(default=False, verbose_name='می\u200cتواند حذف کند')),
                ('can_manage_comments', models.BooleanField(default=False, verbose_name='می\u200cتواند کامنت\u200cها را مدیریت کند')),
                ('can_manage_users', models.BooleanField(default=False, verbose_name='می\u200cتواند کاربران را مدیریت کند')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نقش کاربر',
                'verbose_name_plural': 'نقش\u200cهای کاربری',
            },
        ),
    ]
