# Generated by Django 4.0.10 on 2025-12-03 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='نشانی')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی بلاگ',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای بلاگ',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام برچسب')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'برچسب بلاگ',
                'verbose_name_plural': 'برچسب\u200cهای بلاگ',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='نشانی')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('excerpt', models.TextField(max_length=500, verbose_name='خلاصه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='تصویر')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'آرشیو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='برجسته')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('views', models.IntegerField(default=0, verbose_name='تعداد بازدیدها')),
                ('likes', models.IntegerField(default=0, verbose_name='تعداد پسندیدگی')),
                ('author', models.ForeignKey(limit_choices_to={'blogauthor__is_active': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory', verbose_name='دسته\u200cبندی')),
                ('tags', models.ManyToManyField(blank=True, to='blog.blogtag', verbose_name='برچسب\u200cها')),
            ],
            options={
                'verbose_name': 'پست بلاگ',
                'verbose_name_plural': 'پست های بلاگ',
                'ordering': ['-published_at', '-created_at'],
                'permissions': [('can_publish', 'می\u200cتواند منتشر کند'), ('can_archive', 'می\u200cتواند آرشیو کند')],
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='نویسنده')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('content', models.TextField(verbose_name='متن نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'نظر بلاگ',
                'verbose_name_plural': 'نظرات بلاگ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='عکس پروفایل')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='لینک\u200cهای اجتماعی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نویسنده بلاگ',
                'verbose_name_plural': 'نویسندگان بلاگ',
            },
        ),
    ]
