# Generated by Django 5.2.9 on 2025-12-03 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'verbose_name': '✍️ نویسنده بلاگ', 'verbose_name_plural': '✍️ نویسندگان بلاگ'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': '📁 دسته\u200cبندی بلاگ', 'verbose_name_plural': '📁 دسته\u200cبندی\u200cهای بلاگ'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-published_at', '-created_at'], 'permissions': [('can_publish', 'می\u200cتواند منتشر کند'), ('can_archive', 'می\u200cتواند آرشیو کند')], 'verbose_name': 'پست بلاگ', 'verbose_name_plural': 'پست های بلاگ'},
        ),
        migrations.AlterModelOptions(
            name='blogtag',
            options={'verbose_name': '🏷️ برچسب بلاگ', 'verbose_name_plural': '🏷️ برچسب\u200cهای بلاگ'},
        ),
    ]
