# Generated by Django 5.2.9 on 2026-06-28 12:10

from django.db import migrations, models


def copy_existing_persian_content(apps, schema_editor):
    BlogPost = apps.get_model('blog', 'BlogPost')
    for post in BlogPost.objects.all().iterator():
        changed = False
        if not post.title_fa and post.title:
            post.title_fa = post.title
            changed = True
        if not post.content_fa and post.content:
            post.content_fa = post.content
            changed = True
        if not post.excerpt_fa and post.excerpt:
            post.excerpt_fa = post.excerpt
            changed = True
        if changed:
            post.save(update_fields=['title_fa', 'content_fa', 'excerpt_fa'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogauthor_options_alter_blogcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_de',
            field=models.TextField(blank=True, verbose_name='Content (German)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_fa',
            field=models.TextField(blank=True, verbose_name='Content (Persian)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_de',
            field=models.TextField(blank=True, max_length=500, verbose_name='Excerpt (German)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_fa',
            field=models.TextField(blank=True, max_length=500, verbose_name='Excerpt (Persian)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_de',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (German)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_fa',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (Persian)'),
        ),
        migrations.RunPython(copy_existing_persian_content, migrations.RunPython.noop),
    ]
