# Generated by Django 5.2.14 on 2026-06-28 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_english_content_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostDetailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/details/', verbose_name='Detail image')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Image title')),
                ('content', models.TextField(blank=True, verbose_name='Image text')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_images', to='blog.blogpost', verbose_name='Blog post')),
            ],
            options={
                'verbose_name': 'Blog detail image',
                'verbose_name_plural': 'Blog detail images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
