# Generated by Django 5.2.9 on 2026-06-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpostdetailimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='blog/audio/', verbose_name='Audio file'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='audio_url',
            field=models.URLField(blank=True, verbose_name='Audio URL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='blog/video/', verbose_name='Video file'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Video URL'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
    ]
