# Generated by Django 5.2.14 on 2026-06-29 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogpost_audio_file_blogpost_audio_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'verbose_name': 'âœ\x8dï¸\x8f Ù†ÙˆÛŒØ³Ù†Ø¯Ù‡ Ø¨Ù„Ø§Ú¯', 'verbose_name_plural': 'âœ\x8dï¸\x8f Ù†ÙˆÛŒØ³Ù†Ø¯Ú¯Ø§Ù† Ø¨Ù„Ø§Ú¯'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'ðŸ“\x81 Ø¯Ø³ØªÙ‡â€ŒØ¨Ù†Ø¯ÛŒ Ø¨Ù„Ø§Ú¯', 'verbose_name_plural': 'ðŸ“\x81 Ø¯Ø³ØªÙ‡â€ŒØ¨Ù†Ø¯ÛŒâ€ŒÙ‡Ø§ÛŒ Ø¨Ù„Ø§Ú¯'},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ù†Ø¸Ø± Ø¨Ù„Ø§Ú¯', 'verbose_name_plural': 'Ù†Ø¸Ø±Ø§Øª Ø¨Ù„Ø§Ú¯'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-published_at', '-created_at'], 'permissions': [('can_publish', 'Ù…ÛŒâ€ŒØªÙˆØ§Ù†Ø¯ Ù…Ù†ØªØ´Ø± Ú©Ù†Ø¯'), ('can_archive', 'Ù…ÛŒâ€ŒØªÙˆØ§Ù†Ø¯ Ø¢Ø±Ø´ÛŒÙˆ Ú©Ù†Ø¯')], 'verbose_name': 'Ù¾Ø³Øª Ø¨Ù„Ø§Ú¯', 'verbose_name_plural': 'Ù¾Ø³Øª Ù‡Ø§ÛŒ Ø¨Ù„Ø§Ú¯'},
        ),
        migrations.AlterModelOptions(
            name='blogtag',
            options={'verbose_name': 'ðŸ\x8f·ï¸\x8f Ø¨Ø±Ú†Ø³Ø¨ Ø¨Ù„Ø§Ú¯', 'verbose_name_plural': 'ðŸ\x8f·ï¸\x8f Ø¨Ø±Ú†Ø³Ø¨â€ŒÙ‡Ø§ÛŒ Ø¨Ù„Ø§Ú¯'},
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Ø¨ÛŒÙˆÚ¯Ø±Ø§Ù\x81ÛŒ'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ØªØ§Ø±ÛŒØ® Ø§ÛŒØ¬Ø§Ø¯'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ù\x81Ø¹Ø§Ù„'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Ø¹Ú©Ø³ Ù¾Ø±ÙˆÙ\x81Ø§ÛŒÙ„'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ù„ÛŒÙ†Ú©â€ŒÙ‡Ø§ÛŒ Ø§Ø¬ØªÙ…Ø§Ø¹ÛŒ'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ú©Ø§Ø±Ø¨Ø±'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='Ø±Ù†Ú¯'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='ØªÙˆØ¶ÛŒØ\xad'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ù†Ø§Ù… Ø¯Ø³ØªÙ‡â€ŒØ¨Ù†Ø¯ÛŒ'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Ù†Ø´Ø§Ù†ÛŒ'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Ù†ÙˆÛŒØ³Ù†Ø¯Ù‡'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='content',
            field=models.TextField(verbose_name='Ù…ØªÙ† Ù†Ø¸Ø±'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ØªØ§Ø±ÛŒØ® Ø§ÛŒØ¬Ø§Ø¯'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Ø§ÛŒÙ…ÛŒÙ„'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='ØªØ§ÛŒÛŒØ¯ Ø´Ø¯Ù‡'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost', verbose_name='Ù¾Ø³Øª'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(limit_choices_to={'blogauthor__is_active': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ù†ÙˆÛŒØ³Ù†Ø¯Ù‡'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory', verbose_name='Ø¯Ø³ØªÙ‡â€ŒØ¨Ù†Ø¯ÛŒ'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='Ù…Ø\xadØªÙˆØ§'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ØªØ§Ø±ÛŒØ® Ø§ÛŒØ¬Ø§Ø¯'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(max_length=500, verbose_name='Ø®Ù„Ø§ØµÙ‡'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='ØªØµÙˆÛŒØ±'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Ø¨Ø±Ø¬Ø³ØªÙ‡'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='ØªØ¹Ø¯Ø§Ø¯ Ù¾Ø³Ù†Ø¯ÛŒØ¯Ú¯ÛŒ'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ØªØ§Ø±ÛŒØ® Ø§Ù†ØªØ´Ø§Ø±'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Ù†Ø´Ø§Ù†ÛŒ'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='ÙˆØ¶Ø¹ÛŒØª'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.blogtag', verbose_name='Ø¨Ø±Ú†Ø³Ø¨â€ŒÙ‡Ø§'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Ø¹Ù†ÙˆØ§Ù†'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='ØªØ§Ø±ÛŒØ® Ø¨Ø±ÙˆØ²Ø±Ø³Ø§Ù†ÛŒ'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='views',
            field=models.IntegerField(default=0, verbose_name='ØªØ¹Ø¯Ø§Ø¯ Ø¨Ø§Ø²Ø¯ÛŒØ¯Ù‡Ø§'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ù†Ø§Ù… Ø¨Ø±Ú†Ø³Ø¨'),
        ),
    ]
