# Generated by Django 5.2.9 on 2026-06-29 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogauthor_options_alter_blogcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'verbose_name': 'نویسنده بلاگ', 'verbose_name_plural': 'نویسندگان بلاگ'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'دسته بندی بلاگ', 'verbose_name_plural': 'دسته بندی های بلاگ'},
        ),
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['-created_at'], 'verbose_name': ' نظربلاگ', 'verbose_name_plural': 'نظرات بلاگ'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['-published_at', '-created_at'], 'permissions': [('can_publish', 'میتواند منتشر شود¯'), ('can_archive', 'میتواند آرشیو شود')], 'verbose_name': 'پست بلاگ', 'verbose_name_plural': 'پست های بلاگ'},
        ),
        migrations.AlterModelOptions(
            name='blogpostdetailimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'تصویر جزییات بلاگ', 'verbose_name_plural': 'تصاویر جزییات بلاگ'},
        ),
        migrations.AlterModelOptions(
            name='blogtag',
            options={'verbose_name': ' برچسب بلاگ ', 'verbose_name_plural': 'برچسب های بلاگ'},
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='bio',
            field=models.TextField(blank=True, verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, verbose_name='لینک شبکه اجتماعی'),
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دسته بندی  '),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='نشانی'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='author',
            field=models.CharField(max_length=100, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='content',
            field=models.TextField(verbose_name=' متن نظر'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost', verbose_name='پست'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(limit_choices_to={'blogauthor__is_active': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.blogcategory', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(max_length=500, verbose_name='خلاصه'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='برجسته'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='تعداد لایک'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='نشانی/لینک'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.blogtag', verbose_name='برچسب ها'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی/ویرایش'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='views',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدیدکنندگان'),
        ),
        migrations.AlterField(
            model_name='blogpostdetailimage',
            name='content',
            field=models.TextField(blank=True, verbose_name=' متن تصویر  '),
        ),
        migrations.AlterField(
            model_name='blogpostdetailimage',
            name='image',
            field=models.ImageField(upload_to='blog/details/', verbose_name='جزییات تصویر'),
        ),
        migrations.AlterField(
            model_name='blogpostdetailimage',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='blogpostdetailimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_images', to='blog.blogpost', verbose_name='پست بلاگ'),
        ),
        migrations.AlterField(
            model_name='blogpostdetailimage',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان تصویر  '),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام برچسب'),
        ),
    ]
