# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_blogcomment_options_blogcomment_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="تایید شده"),
        ),
    ]
