# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_blogcomment_pending_by_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="is_approved",
            field=models.BooleanField(default=True, verbose_name="تایید شده"),
        ),
    ]
