# Generated by Django 5.2.14 on 2026-07-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogcomment_auto_publish_by_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_on_homepage',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی'),
        ),
    ]
