# Generated by Django 5.2.14 on 2026-06-30 01:11

import django.core.files.storage
import django.db.models.deletion
import downloads.models
import downloads.validators
import pathlib
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, validators=[downloads.validators.validate_clean_text])),
                ('extension', models.CharField(max_length=20, unique=True)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('max_size_mb', models.PositiveIntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Allowed file type',
                'verbose_name_plural': 'Allowed file types',
                'ordering': ('extension',),
            },
        ),
        migrations.CreateModel(
            name='DownloadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, validators=[downloads.validators.validate_clean_text])),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True, validators=[downloads.validators.validate_clean_text])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Download category',
                'verbose_name_plural': 'Download categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DownloadPageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_notice_text', models.TextField(default='For your security, you do not need to enter your email address. Only your name is required.', validators=[downloads.validators.validate_clean_text])),
                ('comments_enabled', models.BooleanField(default=True)),
                ('reactions_enabled', models.BooleanField(default=True)),
                ('comment_moderation_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Download page setting',
                'verbose_name_plural': 'Download page settings',
            },
        ),
        migrations.CreateModel(
            name='DownloadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180, validators=[downloads.validators.validate_clean_text])),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('windows', 'Windows'), ('config', 'Config'), ('other', 'Other')], default='other', max_length=20)),
                ('version', models.CharField(blank=True, max_length=50, validators=[downloads.validators.validate_clean_text])),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('E:/Desktop/pouriabaghban/protected_media')), upload_to=downloads.models.download_upload_to)),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False)),
                ('file_extension', models.CharField(blank=True, editable=False, max_length=20)),
                ('description', models.TextField(blank=True, validators=[downloads.validators.validate_clean_text])),
                ('changelog', models.TextField(blank=True, validators=[downloads.validators.validate_clean_text])),
                ('installation_guide', models.TextField(blank=True, validators=[downloads.validators.validate_clean_text])),
                ('is_latest', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_login', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='allowed_downloads', to='auth.group')),
                ('allowed_users', models.ManyToManyField(blank=True, related_name='allowed_downloads', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='downloads.downloadcategory')),
            ],
            options={
                'verbose_name': 'Download item',
                'verbose_name_plural': 'Download items',
                'ordering': ('-is_latest', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='DownloadComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, validators=[downloads.validators.validate_clean_text])),
                ('comment', models.TextField(validators=[downloads.validators.validate_clean_text])),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('download_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='downloads.downloaditem')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('download_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='downloads.downloaditem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-downloaded_at',),
            },
        ),
        migrations.CreateModel(
            name='DownloadReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('broken_heart', 'Broken heart')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('download_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='downloads.downloaditem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
