# Generated by Django 5.2.14 on 2026-06-30 01:11

import admin_chat.models
import django.db.models.deletion
import downloads.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, validators=[downloads.validators.validate_clean_text], verbose_name='نام اتاق')),
                ('room_type', models.CharField(choices=[('group', 'گروهی'), ('private', 'خصوصی')], default='group', max_length=20, verbose_name='نوع اتاق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('participants', models.ManyToManyField(blank=True, limit_choices_to={'is_staff': True}, related_name='chat_rooms', to=settings.AUTH_USER_MODEL, verbose_name='اعضا')),
            ],
            options={
                'verbose_name': 'اتاق چت',
                'verbose_name_plural': 'اتاق\u200cهای چت',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, validators=[downloads.validators.validate_clean_text], verbose_name='متن پیام')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='خوانده شده توسط')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='admin_chat.chatroom', verbose_name='اتاق')),
            ],
            options={
                'verbose_name': 'پیام چت',
                'verbose_name_plural': 'پیام\u200cهای چت',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=admin_chat.models.chat_attachment_upload_to, validators=[admin_chat.models.validate_chat_attachment_extension], verbose_name='فایل')),
                ('original_filename', models.CharField(max_length=255, verbose_name='نام اصلی فایل')),
                ('content_type', models.CharField(blank=True, max_length=150, verbose_name='نوع محتوا')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='حجم')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان آپلود')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='admin_chat.chatmessage', verbose_name='پیام')),
            ],
            options={
                'verbose_name': 'ضمیمه پیام',
                'verbose_name_plural': 'ضمیمه\u200cهای پیام',
                'ordering': ('uploaded_at',),
            },
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_type', '-created_at'], name='admin_chat__room_ty_a4275b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', '-timestamp'], name='admin_chat__room_id_dc4ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', '-timestamp'], name='admin_chat__sender__d951b6_idx'),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message', 'uploaded_at'], name='admin_chat__message_833f7e_idx'),
        ),
    ]
