# Generated by Django 5.2.14 on 2026-07-01 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', '-id'], name='admin_chat__room_id_ee6a49_idx'),
        ),
    ]
